{% set name = "kauth" %}
{% set version = "6.0.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kauth-{{ version }}.tar.xz
  sha256: 66046698d2584692d5397a6ec808b2c9f8b7882a0f85233be9cd69283d03c768

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kauth', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - qt
    - kcoreaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Auth.so

about:
  home: https://api.kde.org/frameworks/kauth/html/index.html
  license: BSD-3-Clause AND LGPL-2.0-or-later AND LGPL-2.1-or-later
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  summary: Execute actions as privileged user
  description: |
    KAuth provides a convenient, system-integrated way to offload actions that
    need to be performed as a privileged user (root, for example) to small
    (hopefully secure) helper utilities.
  doc_url: http://techbase.kde.org/Development/Tutorials/KAuth/KAuth_Basics
  dev_url: https://cgit.kde.org/kauth.git/tree

extra:
  recipe-maintainers:
    - scopatz
