{% set name = "kauth" %}
{% set version = "5.67.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kauth-{{ version }}.tar.xz
  sha256: 4f4a0323adcfdc6f80c38c289a73a3b7af6bf5141acd80712eb669b6ffb8bcc3

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kauth', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - qt
    - kcoreaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Auth.so

about:
  home: https://api.kde.org/frameworks/kauth/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'Execute actions as privileged user'
  description: |
    KAuth provides a convenient, system-integrated way to offload actions that
    need to be performed as a privileged user (root, for example) to small
    (hopefully secure) helper utilities.
  doc_url: http://techbase.kde.org/Development/Tutorials/KAuth/KAuth_Basics
  dev_url: https://cgit.kde.org/kauth.git/tree

extra:
  recipe-maintainers:
    - scopatz
